### ISSUE TITLE
Carrying 2 handed items in 1 hand

### ISSUE THREAD

**Issue by LordIgnis** [IcyRelic/LethalMenu#1]
**Description**
Being able to carry 2 handed items in 1 hand

**Use Case**
Being able to carry multiple 2 handed items at once

**Additional context**
This feature is noticeably missing despite just about everything else you could want in a cheat menu for this game being present

**Comment by IcyRelic** [comment]
I will add this

**Comment by IcyRelic** [comment]
Completed. Update has been committed here. Will appear in v1.3.1
