### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Celebat154234** [IcyRelic/LethalMenu#100]
**Describe the bug**
the function of teleporting all loot from the map to a point does not work correctly; loot appears but other players still find loot during the clearing process.

**LethalMenu Version:** [1.3.2]
**Game Version:** [v47]

**Steps To Reproduce**
When using the function, not all loot is teleported, since players still find it in the world.

**Comment by IcyRelic** [comment]
The loot being teleported is client sided. Only you can see it. If you pick it all up and drop it they won't find any inside.
