### ISSUE TITLE
[BUG] Cannot inject into game

### ISSUE THREAD

**Issue by z0rliss** [IcyRelic/LethalMenu#103]
**Describe the bug**
When I run inject.bat, the CMD window opens and then provides an error and instantly terminates

**LethalMenu Version:** 1.4.0
**Game Version:** v49

**Steps To Reproduce**
Run the inject.bat file

**The error**
"Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'SharpMonoInjector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. at SharpMonoInjector.Console.Program.Main(String[] args)"

**Additional context**
I extracted it already too

**Comment by Dustin21335** [comment]
Try this:
https://icyrelic.com/release/lethalmenu/LethalMenuAssistant.zip

**Comment by z0rliss** [comment]
It was my antivirus, forgot to turn it off.
