### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by y0ujinDev** [IcyRelic/LethalMenu#104]
**Describe the bug**

**LethalMenu Version:** 1.4.1
**Game Version:** v49

**Steps To Reproduce**
After successfully settling the accounts on the deadline, the operation of the ship's landing and launching lever has become slow. <<

Most of the modifications were made in the recent commit, but it's still slow right after the close.

**Screenshots**

**Additional context**

**Comment by IcyRelic** [comment]
Fixed in the following commit
https://github.com/IcyRelic/LethalMenu/commit/c8856a278198671e16512be304e4b49372a6da6e
