### ISSUE TITLE
installation??

### ISSUE THREAD

**Issue by koala1014** [IcyRelic/LethalMenu#118]
how the hell do i install it? i've tried just putting the folder in the bepinex plugins that didnt work, just in the main folder for lethal company, also didnt work

**Comment by koala1014** [comment]
also tried with the things INSIDE the LethalMenu main folder in plugins and main lethalcompany folder

**Comment by koala1014** [comment]
please someone help i've been trying since i commented  2 hours ago

**Comment by Dustin21335** [comment]
https://www.unknowncheats.me/forum/lethal-company/615575-lethal-menu-lethal-company-cheat.html or https://icyrelic.com/release/lethalmenu/LethalMenuAssistant.zip

**Comment by Dustin21335** [comment]
you open lethal company and run inject.bat or open lethal company and click inject on the lethalmenu assistant
