### ISSUE TITLE
[BUG] fps drop

### ISSUE THREAD

**Issue by SquattingDoggo** [IcyRelic/LethalMenu#12]
fps drop when u r in front of the puffer

**Comment by SquattingDoggo** [comment]
i have last update*

**Comment by tonyluCM** [comment]
Same issue^

**Comment by SquattingDoggo** [comment]
small update, fps drop when near a lot of mosters

**Comment by IcyRelic** [comment]
> small update, fps drop when near a lot of mosters

how many is a lot?

**Comment by SquattingDoggo** [comment]
5/6

**Comment by IcyRelic** [comment]
I've spawned like 100 Mimics and sti have 60 fps. So I doubt 5-6 would do much to me. 

What Map and what enemy types are you trying
Also inside or outside

**Comment by SquattingDoggo** [comment]
confirmed puffers make u lag, i've tried again

**Comment by IcyRelic** [comment]
Unable to replicate this ang further
