### ISSUE TITLE
[BUG] Unlockables manager

### ISSUE THREAD

**Issue by Lchaxlover** [IcyRelic/LethalMenu#120]
So when I open the unlockables manager 90% of the time it bugs out and doesn't work. It just is a little piece of it in the corner of my screen 

Im using the latest version of both the menu and game

![Lethal Company 3_25_2024 1_21_00 PM](https://github.com/IcyRelic/LethalMenu/assets/164419073/b691f0da-caf3-4911-8089-c0db8839df97)

**Comment by Dustin21335** [comment]
you opened the manager while in the main menu or left the game with it open
