### ISSUE TITLE
[BUG] Moon and Unlockable Manager

### ISSUE THREAD

**Issue by Netshh** [IcyRelic/LethalMenu#135]
No new updated suit in unlockable manager, and the moon manager is buggin. also i forgot to mention the shoplifter cheat does nothing, my money still spended after buying something.

https://github.com/IcyRelic/LethalMenu/assets/93586570/1074f582-28de-4356-92d1-6642b4de6739

**Comment by Dustin21335** [comment]
This is fixed if you compile the github it will be fixed soon if you don't want to do that when we update LethalMenu Assistant and Unknown Cheats
