### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KomiiFN** [IcyRelic/LethalMenu#139]
**Describe the bug**
Hello I did notice that moon manger is blank and add credits only works as host.

**LethalMenu Version:** [(v49) Menu v1.4.2 ]
**Game Version:** [ V50 ]

**Steps To Reproduce**
Click server then click moon manger on the right.

**Screenshots**
N/A

**Additional context**
Sorry for whoever has to read this my writing is terrible

**Comment by Dustin21335** [comment]
add credits is host only

moon manager is fixed in the next update
