### ISSUE TITLE
[Feature] :D

### ISSUE THREAD

**Issue by KomiiFN** [IcyRelic/LethalMenu#140]
**Description**
Hello, these are all the features I want you to add, Bunny hop suit in the upgrade tab, anti- dressgirl in enemy tab (prevents her from chasing you,) respawn, Teleport To Ship in self tab, and ANTI-KICK, If its not possible oh well. 

**Use Case**
Explain how this feature would improve this project or benefit users.
N/A

**Additional context**
I do kind of know how to code I tried to make a piece of code that is just modified respawn  

            public static void RespawnLocalPlayer() 
            {
                PlayerControllerB localPlayer = Instance.localPlayer;
                if (!localPlayer) return;

you can you this code Idc

This way longer than I was expecting .💀  
also side note I'm 90% sure you go invisible if you use this.

**Comment by Dustin21335** [comment]
Anti- dressgirl in enemy tab (prevents her from chasing you,) 
-Just kill her

Bunny hop suit in the upgrade tab
-Added in next update or compile github

Teleport To Ship in self tab
-It's already in self tab 😭
