### ISSUE TITLE
[BUG] NoClip FPS drop

### ISSUE THREAD

**Issue by zerevoidd** [IcyRelic/LethalMenu#15]
**Describe the bug**
Fps drops to below 10 while using noclip

**LethalMenu Version:** 1.3.0
**Game Version:** v45-v49 (applies to all recent updates)_

**Steps To Reproduce**
Turn on noclip and fly around

**Screenshots**

**Additional context**

**Comment by IcyRelic** [comment]
Confirmed issue. 

Seems to be intermittent

**Comment by SquattingDoggo** [comment]
coil+puffer fps drop too

**Comment by SquattingDoggo** [comment]
but is totaly random

**Comment by IcyRelic** [comment]
Fixed NoClip fps drops.
