### ISSUE TITLE
[not a bug] How do I run this?

### ISSUE THREAD

**Issue by Stag1** [IcyRelic/LethalMenu#16]
How do I run this?
I don't know how to compile or code, just don't feel like waiting for the slow mods on unknowncheats to approve it.

**Comment by IcyRelic** [comment]
[Guide](https://github.com/IcyRelic/LethalMenu/wiki/Compiling-The-Project)

[Youtube Video](https://www.youtube.com/watch?v=-9j_okrjaq0)
