### ISSUE TITLE
[request] can you add a guide on how to compile?

### ISSUE THREAD

**Issue by ottovef** [IcyRelic/LethalMenu#17]
i have never compiled anything and am getting errors. can you add a quick guide on how to compile?

**Comment by IcyRelic** [comment]
[Step By Step Guide](https://github.com/IcyRelic/LethalMenu/wiki/Compiling-The-Project)

[Youtube Video](https://www.youtube.com/watch?v=-9j_okrjaq0)

**Comment by ottovef** [comment]
> [Step By Step Guide](https://github.com/IcyRelic/LethalMenu/wiki/Compiling-The-Project)
> 
> [Youtube Video](https://www.youtube.com/watch?v=-9j_okrjaq0)

just saw it, appreciate your efforts a lot. sorry for necroposting, just wanted to express how greatful i am
