### ISSUE TITLE
[BUG] Cannot Compile

### ISSUE THREAD

**Issue by zerevoidd** [IcyRelic/LethalMenu#19]
**Describe the bug**
Still cannot properly compile this solution even following the proper steps

**LethalMenu Version:** v1.3.2
**Game Version:** N/A

**Steps To Reproduce**
1) Copy and paste all files from the "Managed" folder of Lethal Company's local files to the "Resources" folder within the Lethal menu folder.
2) Copy and paste the proper Harmony.dll file (in this case Harmony472) into the resources folder as well
3) Run the LethalMenuSln.sln file and build the project as a x64 release

**Screenshots**
![image](https://github.com/IcyRelic/LethalMenu/assets/97651456/ddafd138-9fb7-4797-a278-12cc58516df5)

**Additional context**

**Comment by tonyluCM** [comment]
change the line with error from return []; to return null;

**Comment by IcyRelic** [comment]
Not sure why this errors on others end. Must be editor related. I changed the code so future issues are minimal.
