### ISSUE TITLE
[Feature] Lock player head and enable mouse cursor when menu is open

### ISSUE THREAD

**Issue by tedzify** [IcyRelic/LethalMenu#2]
**Description**
---
When the menu is open, the player head is locked preventing them from looking around and at the same time, the mouse cursor will be visible to allow easier access to the menu without needing to press `Esc` everytime users open the menu to use its functions.

**Use Case**
---
Enabled by default if the menu is open.

**Additional context**
---
None.

**Comment by IcyRelic** [comment]
There is a Toggle cursor keybind currently. I will make it also occur when the menu is opened or closed

**Comment by tedzify** [comment]
> There is a Toggle cursor keybind currently.

Oh, it seems I didn't notice that setting. Then, just making it toggle automatically would be much appreciated.

**Comment by IcyRelic** [comment]
Completed.
