### ISSUE TITLE
Spam the PJ plushie

### ISSUE THREAD

**Issue by tuiio** [IcyRelic/LethalMenu#20]
PJ Plush Spam
**Description**
Clearly describe the new feature or enhancement you are proposing. Nah

**Use Case**
Explain how this feature would improve this project or benefit users. Annoying lol

**Additional context**
Add any other context or screenshots about the feature request here. Nah

**Comment by FancyDucc** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by IcyRelic** [comment]
Completed. Super annoying, super funny lol. I had a good laugh
