### ISSUE TITLE
I can provide Chinese translation

### ISSUE THREAD

**Issue by 19123978** [IcyRelic/LethalMenu#22]
Dear author, hello. I would like to provide you with a Chinese translation to make this cheat better

**Comment by 19123978** [comment]
If possible, please send me your Telegram contact information and I will contact youThank you

**Comment by 19123978** [comment]
是的，就是机翻+人工修改，怎么了

**Comment by IcyRelic** [comment]
Too funny. After I posted the menu on UC it got uploaded on so many random sites. Some choose to say developed by icyrelic others don't bother. But it's rather concerning.
