### ISSUE TITLE
[BUG] Entity Controlling Overall

### ISSUE THREAD

**Issue by zerevoidd** [IcyRelic/LethalMenu#23]
**Describe the bug**
Very limited control over any entity you select and camera placement is buggy as well, the only thing you can really do when controlling an entity is temporarily stop it from moving, otherwise it just continues as it would normally.
**LethalMenu Version:** v1.3.2
**Game Version:* v49

**Steps To Reproduce**
Try to control any entity such as the bracken

**Screenshots**

**Additional context**

**Comment by IcyRelic** [comment]
Closing, please use #95 for reference.
