### ISSUE TITLE
[Feature] Loot Manager

### ISSUE THREAD

**Issue by D1GQ** [IcyRelic/LethalMenu#30]
**Description**
Add a new pop-up window for managing loot that is currently on the ground

**Use Case**
With this you could add a pickup option on each item/loot, for example if there is a stop sign on the ground in the factory you can force pick up so you have a weapon at the beginning without having to be host to spawn it in.

**Comment by Azomatox** [comment]
You could also do stuff like.. maybe delete the item by sending it far far away? (Don't know if thats possible)

Or lock it from being picked up (maybe the pickup box is like sent away (Don't know either if thats possible))

**Comment by TKarambit** [comment]
These Feature's Are Host Only Option's

**Comment by D1GQ** [comment]
> These Feature's Are Host Only Option's

It could be possible without being host. you could try to manipulate the game too think that the player is picking up the item than dropping it while at a certain coordinate.

**Comment by Dustin21335** [comment]
Added :D
