### ISSUE TITLE
[BUG] "build anywhere" feature doesn't work

### ISSUE THREAD

**Issue by CoolDEDXD** [IcyRelic/LethalMenu#32]
**Describe the bug**
The “build anywhere” function now does not work correctly, you cannot pull objects out of the ship, for example, a “portal”, but the terminal can be pulled out of the ship and placed anywhere, but after you place the terminal you cannot take it further.

**LethalMenu Version:** [1.3.2]
**Game Version:** [v49]

**Steps To Reproduce**
Turn on the “build anywhere” function, launch the ship onto the planet and take a portal or terminal or whatever you like and pull it behind the ship.

**Screenshots**

![Снимок экрана (1235)](https://github.com/IcyRelic/LethalMenu/assets/156037376/e79fe573-e629-4e8a-b8ba-754c76747d05)

![Снимок экрана (1236)](https://github.com/IcyRelic/LethalMenu/assets/156037376/0aa65c7e-bad1-439e-8daf-b4357aa650eb)

**Additional context**
in LethalMenu 1.2.1 and game version 45, the “build anywhere” function worked

**Comment by Ezy2** [comment]
how'd you get the 1.3.2v to open

**Comment by CoolDEDXD** [comment]
> как вам удалось открыть 1.3.2v

https://github.com/IcyRelic/LethalMenu/wiki/Compiling-The-Project

here are instructions on how to do this

**Comment by CoolDEDXD** [comment]
accidentally closed

**Comment by IcyRelic** [comment]
This is a bug with the game itself. Version 47+ broke this feature. It's unknown at this time if it can be resolved.

**Comment by Dustin21335** [comment]
This will be fixed in the next update :D
