### ISSUE TITLE
LCVR Compatibility 

### ISSUE THREAD

**Issue by LordIgnis** [IcyRelic/LethalMenu#33]
**Description**
Basically, just a Compatibility update to make this more easily usable with Lethal Company VR, immersive menu in game, maybe a floating stream deck like bar that you could bind toggles or execute commands like "Unlock Door" and "Kill Nearby Enemies"

**Use Case**
Players who want to play in VR but don't want to give up the massive benefits Lethal Menu offers the user

**Additional context**
I REALIZE THIS IS A HUGE ASK FOR A PROJECT LIKE THIS and I know the likeliness of it happening is low. Lethal Menu can technically be used in VR with some caveats, like the ESP not working (Chams does work but you have to crank up the distance for it to be of use),  No Interact Cooldown breaks interactions in VR (I don't think it would be possible to fix this with how LCVR is designed). I'm not super VR savvy so I have no idea if this will ever be possible or if there is a way around the issues I've had in my testing, but I wanted to put it out there that at the very least that there is someone interested in this as a possibility.

Thanks for your time regardless and keep up the great work on this project

**Comment by IcyRelic** [comment]
I'm not even sure where to begin with this ask, this is my first project. I can do some research but I don't even have a way to test anything as I don't have VR

**Comment by LordIgnis** [comment]
> I'm not even sure where to begin with this ask, this is my first project. I can do some research but I don't even have a way to test anything as I don't have VR

Absolutely I totally get that, I just wanted to put it out there in the off chance that it might be possible, if this never gets looked into, I'm not going to be upset about it. It's kind of out of left field and is a very niche thing to request so please don't feel pressured or anything to look into it if it's out of the realm of possibility. But if you do and need someone to help test it out, I would be happy to help
