### ISSUE TITLE
[Not a BUG] Cant open It with Insert. Any way to change keybinds ?

### ISSUE THREAD

**Issue by BrosofDoom** [IcyRelic/LethalMenu#36]
**Describe the bug**
Cant open the menu with insert button even then i dont know how to change keybinds

**LethalMenu Version:** [ v49 1.3.2]
**Game Version:** [ v49 1.3.2]

**Comment by IcyRelic** [comment]
Yes, there is a config file in the game install folder. Change the config that doesn't say default.
