### ISSUE TITLE
[BUG] I cannot open the menu

### ISSUE THREAD

**Issue by YoungZayed** [IcyRelic/LethalMenu#38]
**Describe the bug**
that when I try to launch the menu i can see on the top left that that it says made my icyrelic and when I click on insert nothing changes
i see nothing nothing open

**LethalMenu Version:** [1.3.2]
**Game Version:** [v49]

**Steps To Reproduce**
Provide detailed steps to reproduce the bug.

**Screenshots**

**Additional context**

**Comment by Ezy2** [comment]
I have the same problem

**Comment by LiuWen4333** [comment]
maybe you are opening a floating software like the MSI Afterburner tool, and it is causing a conflict, try turning it off and then restarting the game.

**Comment by IcyRelic** [comment]
Are you using a laptop?

**Comment by Pabloxrp97max** [comment]
**FIXED:** I had same issue when paired with BepInEx mods --> Dont use BepInEx Game when using this
Still trying to find out a way to inject this .DLL into BepInEx mods and make it work

**Comment by Pabloxrp97max** [comment]
> I have the same issues. Tried deleting all game files to ensure there was no modded data but still didn't work. Did also try uninstalling MSI Afterburner because of the other comment in here, but i still can't manage to open the menu with "insert" even tho i can see that the hack is injected in the top left corner when i'm in game.

try on-screen keyboard to make sure the insert key is pressed

**Comment by doodledane** [comment]
I already tested that. Also i can get every other hack menu for Lethal Company to work where you have to use insert to open menu.

**Comment by IcyRelic** [comment]
Not sure I completely understand this ask. This is NOT a bepinex compatible menu. It will run along side bepin but cannot be injected using bepin and must be injected with sharp mono injector or another injector that works in the same way.
