### ISSUE TITLE
[Feature] HearEveryone

### ISSUE THREAD

**Issue by Dustin21335** [IcyRelic/LethalMenu#39]
**Description**
Clearly describe the new feature or enhancement you are proposing.
You can hear anyone speaking on the map

**Use Case**
Explain how this feature would improve this project or benefit users.
Hearing people in the ship or while in the building when not being anywhere close to them is helpful

**Additional context**
using System;
using GameNetcodeStuff;
using HarmonyLib;
using UnityEngine;

namespace LethalMenu.Cheats
{
    [HarmonyPatch]
    internal class HearEveryone : Cheat
    {
        public override void Update()
        {
            if (!Hack.HearEveryone.IsEnabled() || StartOfRound.Instance.shipIsLeaving) return;

            foreach (PlayerControllerB playerControllerB in StartOfRound.Instance.allPlayerScripts)
            {
                AdjustVoiceSettings(playerControllerB);
            }
        }

        private void AdjustVoiceSettings(PlayerControllerB playerControllerB)
        {
            AudioSource currentVoiceChatAudioSource = playerControllerB.currentVoiceChatAudioSource;
            currentVoiceChatAudioSource.GetComponent<AudioLowPassFilter>().enabled = false;
            currentVoiceChatAudioSource.GetComponent<AudioHighPassFilter>().enabled = false;
            currentVoiceChatAudioSource.panStereo = 0f;
            SoundManager.Instance.playerVoicePitchTargets[(int)((IntPtr)playerControllerB.playerClientId)] = 1f;
            SoundManager.Instance.SetPlayerPitch(1f, unchecked((int)playerControllerB.playerClientId));
            currentVoiceChatAudioSource.spatialBlend = 0f;

            if (playerControllerB.currentVoiceChatAudioSource != null)
            {
                playerControllerB.currentVoiceChatAudioSource.volume = 1f;
            }

            playerControllerB.currentVoiceChatIngameSettings.set2D = true;
        }
    }
}

**Comment by Ezy2** [comment]
That's cool, would is it possible to make it work for dead people too?

**Comment by Azomatox** [comment]
> That's cool, would is it possible to make it work for dead people too?

Project Apparatus has this feature and it works for the dead too.

**Comment by Dustin21335** [comment]
I'll try to make it work for dead people aswell kinda annoying to test it lol

**Comment by IcyRelic** [comment]
Feel free to make a pull request and I'll approve it if you get it working

**Comment by Dustin21335** [comment]
I did a pull request with a few new features :D

**Comment by Dustin21335** [comment]
HearEveryone should be added soon :)
