### ISSUE TITLE
Visual studio requirements

### ISSUE THREAD

**Issue by cmmaio** [IcyRelic/LethalMenu#4]
What requirements do we need to compile from source?

**Comment by IcyRelic** [comment]
![image](https://github.com/IcyRelic/LethalMenu/assets/1262507/04e9b530-ea12-4235-bc80-06c4ba1f2bd4)

You need to add the BaseGame dlls to the BaseGame folder and add Harmony and NewtonsoftJson to the Resources dir

BaseGame dlls can be found in your game install folder "\Lethal Company_Data\Managed"

https://github.com/pardeike/Harmony/releases
https://github.com/JamesNK/Newtonsoft.Json/releases
