### ISSUE TITLE
[BUG] Menu not opening in game when pressing insert

### ISSUE THREAD

**Issue by doodledane** [IcyRelic/LethalMenu#40]
**Describe the bug**
I correctly inject the hack when ingame and can see the purple text in the top left corner "Lethal Menu v1.3.2 by IcyRelic". But whenever i press insert the menu will not open.

**LethalMenu Version:** v1.3.2
**Game Version:** V49

**Steps To Reproduce**
Simple start the game, host a server, inject the hack and press insert.

**Screenshots**
No screenshots.

**Additional context**
I have tested multiple other hacks that uses insert to open menu that works for me. But for some reason i cannot open the menu for this one with insert.

**Comment by doodledane** [comment]
**FIXED**
I tried rebinding INSERT to my mouse and it worked. Maybe developer can use this information or not but anyways that was the only solution to this i found.

**Comment by doodledane** [comment]
> @doodledane are you on a laptop?

No i am on a pc using a bluetooth keyboard.

**Comment by IcyRelic** [comment]
Can you do me a favor and set any keybind to the insert key on your keyboard snd tell me what nut button says it is and what the config says it is

**Comment by doodledane** [comment]
It says Numpad0. It is probably because i use an apple keyboard to a windows computer where the numpad 0 is insert after you press NumLock. I hope that helps.

**Comment by IcyRelic** [comment]
Yes. That does help. But unfortunately that is the wrong 'insert' the insert it calls for is the more dedicated one on a full size keyboard. In the future when I implement languages I'm going to do a first time setup process where when you inject for the first time it will ask you what you want the key to be

**Comment by doodledane** [comment]
Glad i could help. Now that i got it to work, i must say it is the best cheat out there without a doubt!
