### ISSUE TITLE
[Feature] Moon Condition Changer (Expansion to Moon Manager)

### ISSUE THREAD

**Issue by Azomatox** [IcyRelic/LethalMenu#41]
Expanding the moon manager could make its use more practical instead of being a manager that barely anybody uses.

What I propose is that, maybe there could be a sidebar that once selected a moon, could SWITCH conditions for that moon.

This is obviously going to be a host process (you could just make the sidebar invisible if your not the host/add a red text like you've done for Enemy Manager in other people's lobbies.)

For example:

Rend is foggy.
You simply go to the Moon Manager and you select Rend as your target. You then press one of the conditions on the sidebar and it switches it to.. Clear or something.

I don't know if its possible but would make Moon Manager more than a one-time use (in my opinion)

**Comment by IcyRelic** [comment]
I experimented with this awhile ago and while being host I was able to make it eclipsed. For me atleast it appeared normal for others. But monsters did spawn naturally. So sadly this really isn't worth adding. Great suggestions tho
