### ISSUE TITLE
[Feature] Anti-Grief Manager

### ISSUE THREAD

**Issue by Azomatox** [IcyRelic/LethalMenu#42]
**Description**
An Anti-Grief Manager would be nice incase other people are using Menus and you don't want your experience to get ruined. Could also help expand the Menu to legit players who just don't want their credits being turned to the millions for example.

**Use Case**
This feature would benefit the user as it would allow them to have an undisturbed experience.

**Additional context**
For example, an Anti-Grief Credits option. It could lock the current credits to the original number (Any change will be instantly reverted, HOWEVER! to ensure legitimate credits still go through, if the person lands on Gordion, the code halts and once they leave, it turns back on.

(I don't know if its possible but could be nice imo)

**Comment by Azomatox** [comment]
Now that I think about it, it seems impractical and likely wont be considered

**Comment by IcyRelic** [comment]
This idea would be better suited for a standalone mod.
