### ISSUE TITLE
[BUG]Build error

### ISSUE THREAD

**Issue by laodediao** [IcyRelic/LethalMenu#46]
Severity Code Description Item File Line Suppressed Status Details
Error CS0012 Type 'VoicePlayerState' is defined in an unreferenced assembly. A reference to assembly "DissonanceVoip, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" must be added. LethalMenu

**Comment by laodediao** [comment]
I followed the tutorial but I still get the error

**Comment by D1GQ** [comment]
I had the exact same error but it's a simple fix, it seems like they forgot to add "DissonanceVoip.ddl" as a reference in the download, all you have to do is make a new reference to it. You can find it in the "Managed" game files for LC, it's called "DissonanceVoip.ddl"

**Comment by laodediao** [comment]
> 我也遇到了同样的错误，但这是一个简单的修复方法，似乎他们忘记了在下载中添加“DissonanceVoip.ddl”作为引用，您所要做的就是对它进行新的引用。你可以在LC的“托管”游戏文件中找到它，它被称为“DissonanceVoip.ddl”

Thank you, I solved the problem
