### ISSUE TITLE
[Feature] Fix The Monster Possess

### ISSUE THREAD

**Issue by TKarambit** [IcyRelic/LethalMenu#47]
**Description**
Please Add An Feature Where You Can Use The Entity's Special Ability's
Since There's A Mod On Controlling The Entity's
Heres The Keybinds

 if its possible kindly respond please!
 
[LMB : Use 1st Special Ability ]
[RMB : Use 2nd Special Ability ]
[ E : Open Door's ]

**Use Case**
This Fix Would Make The Possessing Monster's More Funner And Hear Out Their Reaction's 

**Additional context**
None

**Comment by Ezy2** [comment]
I agree we need a fix

**Comment by IcyRelic** [comment]
Closing, Please use issue #95 for reference.
