### ISSUE TITLE
[BUG] Togglable enemy types not working

### ISSUE THREAD

**Issue by doodledane** [IcyRelic/LethalMenu#48]
**Describe the bug**
I assume the section in "Settings" called "Enemy Types" is supposed to decide which enemies should have a cham whenever the chams is turned on. When i toggle selected enemies off on the list it still shows all enemies as chams.

**LethalMenu Version:** V1.3.2
**Game Version:** V49

**Steps To Reproduce**
Turn on chams. Toggle the different monsters on and off under "Enemy Types" in "Settings"

**Screenshots**
https://github.com/IcyRelic/LethalMenu/assets/100388170/d1281917-a1e8-4f9b-bd95-47b00c541cb0

**Additional context**
I also tested with Enemy ESP and it does not toggle it off here either. Please correct me if this is not how it's intended to work.

**Comment by IcyRelic** [comment]
Fixed in the latest commit.
