### ISSUE TITLE
[BUG] Game Crashes Occassionally?

### ISSUE THREAD

**Issue by QueenScarletts** [IcyRelic/LethalMenu#49]
I'm not too sure if it's the new update (47) in general or if it's in combination of the menu, I do have ESP on but that's about it. I didnt trigger anything else on the menu.

If it's just the game lemme know and close this I guess, just wanted to make sure you know about it.

**Comment by IcyRelic** [comment]
Does anyone else have this issue? I know it existed a few builds ago. But I havnt crashed recently. I'll continue to monitor and leave this issue open just incase.

**Comment by BloxerExists** [comment]
I also have this issue. My game crashes basically every second round

**Comment by IcyRelic** [comment]
Please send me your player file for the crash

open run, go here %tmp%\ZeekerssRBLX\Lethal Company\Crashes
