### ISSUE TITLE
Can't open menu

### ISSUE THREAD

**Issue by mep478** [IcyRelic/LethalMenu#53]
**Describe the bug**
Cannot open the menu

**2.0.0** [Your Version Here]
**49** [Your Version Here]

**Steps To Reproduce**
Pressing insert doesnt open menu

**Additional context**
There are the mods I have:
AdditionalContentFramework v1.0.3 by AlexCodesGames
AdditionalSuits v2.0.0 by AlexCodesGames
AdvancedCompany v1.0.118 by PotatoePet
BepInExPack v5.4.2100 by BepInEx
ControlCompany v1.0.9 by ControlCompany
CustomFunSuits v1.8.2 by GhostbustingTrio
FrostySuits v1.1.9 by happyfrosty
FrostySuits2 v1.0.9 by happyfrosty
LethalCompany_InputUtils v0.5.5 by Rune580
More_Emotes v1.3.3 by Sligili
More_Suits v1.4.1 by x753
MoreMaterials v1.3.1 by ViViKo
Reptilian_Suit v1.0.1 by Crab_imitation
Runtime_Netcode_Patcher v0.2.5 by Ozone
Skinwalkers v4.0.1 by RugbugRedfern
Some_Suits v1.0.6 by Kats
SuitSaver v1.1.4 by Hexnet111
TooManySuits v1.0.5 by Verity
ViViKoCosmetics v1.5.0 by ViViKo
YippeeMod v1.2.3 by sunnobunno
zakharslethalmenu v2.0.0 by hacks

**Comment by mep478** [comment]
I also tried without using any other mods and nothing worked

**Comment by TKarambit** [comment]
Well Then, Its A Bit Complicated For Me I Think You Should Really Just Unistall Some Mod's To Make It Work Or Just Disable Them Using The Thunderstore Manager

**Comment by IcyRelic** [comment]
are you on a laptop? if so the insert key youre pressing is Numpad0
You can change the key to open the menu in the config located in the game install folder. lethalmenu.config.json
