### ISSUE TITLE
[Feature] Minimap

### ISSUE THREAD

**Issue by FutureXpo** [IcyRelic/LethalMenu#56]
**Description**
Is it possible to add minimap like [this](https://github.com/tyzeron/LethalCompanyMinimap/blob/main/Patches/HUDManagerPatch.cs) for example?

**Use Case**
Using it, it would be easy to see if there is a dead end where you are going.

**Comment by IcyRelic** [comment]
Pretty sure you can just use this mod without others having it.

**Comment by FutureXpo** [comment]
Yeah, it was just offer to add it to mod, but ok
