### ISSUE TITLE
where is the location where the settings are saved?

### ISSUE THREAD

**Issue by a66a66a** [IcyRelic/LethalMenu#58]
i would like to ask where the save location is?

**Comment by D1GQ** [comment]
It is saved where the game files are, this can differ depending on where the game files are when launching the game.

"C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\lethelmenu.config.json"

**Comment by IcyRelic** [comment]
As @D1GQ said its located in the game installation root folder. Lethalmenu.config.json is your config file the default one is just there to overwrite that one if you ever need.

**Comment by a66a66a** [comment]
> It is saved where the game files are, this can differ depending on where the game files are when launching the game.
> 
> "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\lethelmenu.config.json"

thanks
