### ISSUE TITLE
[BUG] Crashing

### ISSUE THREAD

**Issue by SquattingDoggo** [IcyRelic/LethalMenu#6]
fps drop+ crash
 those r my settings
![Screenshot_39](https://github.com/IcyRelic/LethalMenu/assets/155449930/09bdaf00-8803-430e-ba2e-d4a028861f27)
[lethelmenu.config.json](https://github.com/IcyRelic/LethalMenu/files/13853135/lethelmenu.config.json)

**Comment by IcyRelic** [comment]
Looking I to the issue. Seems to be something happening. I have had it crash on my yesterday as well as some issues with esp.

**Comment by IcyRelic** [comment]
@SquattingDoggo  please update to the latest commit and tell me if you have issues still.

**Comment by SquattingDoggo** [comment]
> @SquattingDoggo please update to the latest commit and tell me if you have issues still.

last update if u spawn a lot of monster it will crash

**Comment by IcyRelic** [comment]
> > @SquattingDoggo please update to the latest commit and tell me if you have issues still.
> 
> last update if u spawn a lot of monster it will crash

Are you still getting fps drops?

**Comment by SquattingDoggo** [comment]
> > > @SquattingDoggo please update to the latest commit and tell me if you have issues still.
> > 
> > 
> > last update if u spawn a lot of monster it will crash
> 
> Are you still getting fps drops?

when i spawn a lot of monster yes

**Comment by IcyRelic** [comment]
I think that's just a given.
