### ISSUE TITLE
[BUG] Cannot control monster directionnal imputs 

### ISSUE THREAD

**Issue by M-Gardevoir** [IcyRelic/LethalMenu#7]
**Describe the bug**
Well, as the title says, we cannot control the movement of the monsters. Even if it works (sometimes), the movement is incredibly slow.

**LethalMenu Version:** 1.3.1
**Game Version:** v45 vanilla

**Steps To Reproduce**
Launch a game and try to control an enemy

**Comment by IcyRelic** [comment]
Have you tried changing your movement speed setting under self cheats? You don't have to enable it but atlease move the slider up
