### ISSUE TITLE
[BUG] No Cooldown Interaction

### ISSUE THREAD

**Issue by D1GQ** [IcyRelic/LethalMenu#76]
**Describe the bug**
When No Cooldown is enabled trying to open the doors on the red closet in the ship or doors in general doesn't work, it just makes a noise.

**LethalMenu Version:** [Your Version Here]
**Game Version:** [V49]

**Comment by IcyRelic** [comment]
Im not able to replicate this issue with any combination of NoCooldown/InstantInteract enabled/dissabled.
