### ISSUE TITLE
[Feature] Spanish Language

### ISSUE THREAD

**Issue by tiofeo65** [IcyRelic/LethalMenu#78]
**Description**
Since these are just ideas, I’m going to share mine. I would suggest adding a new language like Spanish.
**Use Case**
The case is that there are Spanish people who also use this, of course everything is understood since I know English, but if we want more people to use this menu it is likely better to add Spanish as people will like it
**Additional context**
This is just a request so it’s not a big deal. I don’t want you to put too much effort into this. Besides, I’m new here and I’m just trying to help.

**Comment by IcyRelic** [comment]
Join the discord we would be glad to have you. The translations are provided by the community using crowdin. Once you join the discord send me a message and I'll add you as a translator and you can provide us the Spanish version

**Comment by tiofeo65** [comment]
Hello!

Thank you for the invitation to join your Discord server and for the opportunity to contribute as a translator. I'm excited to be able to help provide the Spanish version. I will join Discord and send you a message soon.

However, I would like to mention that I am not familiar with Crowdin and how to use it. I would appreciate any guidance or resources that can help me get started with this platform.

Regardless, I am looking forward to contributing and learning in the process.

:)

**Comment by IcyRelic** [comment]
It's okay, I'm brand new to crowin as well. Learning as I go along. It was suggested to use it by another member. Thanks for helping out
