### ISSUE TITLE
[notabug] How to compile this?

### ISSUE THREAD

**Issue by zerevoidd** [IcyRelic/LethalMenu#8]
I'm new to things like this and I'm just curious on how I could compile the latest version of this cheat, has been amazing so far but I'd like to try out the newest versions before UC approves them. Thank you!

This is what happens when I try to compile.
![image](https://github.com/IcyRelic/LethalMenu/assets/97651456/d61c4671-a91c-41d1-aa21-e77548d7b28d)

**Comment by IcyRelic** [comment]
did you change anything accidentally in the GameUtil class?

**Comment by zerevoidd** [comment]
No I did not, I don't know enough about coding to try and change anything myself.

**Comment by IcyRelic** [comment]
can you post a screenshot of the GameUtil class?

**Comment by zerevoidd** [comment]
![image](https://github.com/IcyRelic/LethalMenu/assets/97651456/bd5c5cba-461d-4a72-ae48-55f1e20952a2)

**Comment by Turboriegel** [comment]
Is there an tutorial to compile it with visual studio?

**Comment by SquattingDoggo** [comment]
C:\Users\%username%\Desktop\Lethal Company\Lethal Company_Data\Managed (copy all in managed)
past all there->LethalMenu/Resources
copy 0Harmony.dll from there C:\Users\%username%\Downloads\Harmony.2.2.2.0.zip\net472 and past in LethalMenu/Resources
https://github.com/pardeike/Harmony

**Comment by tedzify** [comment]
Same procedure as [Project Aparatus](https://youtu.be/6AhJQLgt8Jc). Just copy everything into `LethalMenu/Resources`.

**IMPORTANT:** Make sure the `0Harmony.dll` you copy is from the `Harmony.2.2.2.0.zip\net472` folder because this project uses .NET framework 4.7.2.

**Comment by zerevoidd** [comment]
I've done all of this and managed to get a buddy of mine to fix the issue for me by changing the GameUtil.cs. Is anyone else having the same one I posted above?

**Comment by tonyluCM** [comment]
Had the same issue. Changed empty brackets to null seem to fix the issue for me.

**Comment by IcyRelic** [comment]
Will post a step by step tutorial later.
