### ISSUE TITLE
Teleport one item randomly

### ISSUE THREAD

**Issue by TheFatGamer123** [IcyRelic/LethalMenu#84]
**Description**
Should make it that it teleports one item randomly since it picks lowest value to highest, makes it hard to teleport one item since it will keep teleporting the lowest until you have it in your inventory and teleport something else.

**Use Case**
Instead of having to have 4 keys in your inventory to get a different item, can teleport any one item in the factory.

**Comment by Dustin21335** [comment]
Added :D
