### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zerevoidd** [IcyRelic/LethalMenu#9]
**Describe the bug**
Grabbing any "hands full" item and dropping it makes you unable to pick anything else up or scroll through your item list

**LethalMenu Version:** v1.3.1
**Game Version:** v45

**Steps To Reproduce**
Turn on:
Loot through walls
Int through walls
Reach
No Cooldown
Instant interact

Try grabbing a "hands full" item through a wall (most applicable is the large axel)

**Screenshots**
Can't really describe the issue through a screenshot

**Additional context**
These are just the options I had enabled, it may be able to be done with less options enabled

**Comment by SquattingDoggo** [comment]
samew for me

**Comment by IcyRelic** [comment]
Interesting bug. Looking into it

**Comment by SquattingDoggo** [comment]
unplayable if not fix

**Comment by IcyRelic** [comment]
Can you post your config here, I can't replicate the issue on my end

**Comment by tonyluCM** [comment]
It also happened to me when I am not the host.

**Comment by SquattingDoggo** [comment]
[lethelmenu.config.json](https://github.com/IcyRelic/LethalMenu/files/13862064/lethelmenu.config.json)
try to grab and relase big items and small with this coinfig

**Comment by SquattingDoggo** [comment]
but u need to don't be the host

**Comment by IcyRelic** [comment]
> [lethelmenu.config.json](https://github.com/IcyRelic/LethalMenu/files/13862064/lethelmenu.config.json) try to grab and relase big items and small with this coinfig but u need to don't be the host, if u r the host it work fine

I was able to replicate with this config. Working on a fix

**Comment by IcyRelic** [comment]
Fixed
