### ISSUE TITLE
[BUG] virus detection like a christmas baubles

### ISSUE THREAD

**Issue by AleDss1374** [IcyRelic/LethalMenu#98]
ran the program through VirusTotal and the results are kind of worrying... any justification? https://www.virustotal.com/gui/file/d5a3540153ff313bbb6a1ba2f126dba327429e9a6f6330215da697863d84307c

**Comment by IcyRelic** [comment]
Did you even read the label? trojan.msil/dllinject

I take it you scanned sharp mono injector with it. There's no other way to use the hack without injecting it to the game. The source code is publicly available. You can download a compiled version on unknowncheats where they physically and thougherly check it for viruses. Not to mention their extreamly strict rules with things I can and can't do inside of it. Can't even connect to the internet.

**Comment by AleDss1374** [comment]
Sorry, my bad, I didn't pay enough attention. Thank you anyways.
